### ISSUE TITLE
Is it need two stage train 

### ISSUE THREAD

**Issue by ericosmic** [salu133445/bmusegan#1]
If musegan/bmusegan is need two stages train and each stage need change some config parameters (like stage_phase)?

**Comment by salu133445** [comment]
You need to modify the following values of dictionary `SETUP` in `config.py`.

| Key | Value (Stage I) | Value (Stage II) |
| --- | --- | --- |
| 'two_stage_training' | True | True|
| 'training_phase' | 'pretrain' | 'train' |
| 'first_stage_dir' | None | 'path/to/pretrained/model' |

(Usually, `SETUP['first_stage_dir']` can be automatically determined. Just set it to None and see if it works. If not, then specify it manually.)
