### ISSUE TITLE
The error about pretrain data source 'lastfm_alternative_5b_phrase.npy'

### ISSUE THREAD

**Issue by ericosmic** [salu133445/bmusegan#2]
I try use the recommend data source --lastfm_alternative_5b_phrase.npy  for train musegan/bmusegan ,  but it give a error feed : 
![2018-11-02 15-12-11](https://user-images.githubusercontent.com/35327931/47898873-a941b200-deb2-11e8-9a9c-9883be8d5a60.png)
It's seem the dataset is have wrong form,  do you know what the problem in detail.

**Comment by salu133445** [comment]
You need to set `MODEL_CONFIG['num_track']` in `config.py` to 5.
