### ISSUE TITLE
The second stage train problem 

### ISSUE THREAD

**Issue by ericosmic** [salu133445/bmusegan#3]
I tried to train bmusegan model by the source code in musegan github ,  it always stop in the 'initializing variables'  step and jump out .  So I check the source program and find the problem maybe  happen in the main.py  , when we choose  second_stage training phase , the program still jump into first_stage's class GAN and cause the initial wrong .

**Comment by salu133445** [comment]
Could you provide the configuration and error messages so that I can diagnose your problem?

In general, for two stage training, you need to set `SETUP['two_stage_training']` to True and `CONIFG['training_phase']` to 'pretrain' in the first stage. After you complete the first stage training, you then set `CONIFG['training_phase']` to 'train' for the second stage training.

**Comment by ericosmic** [comment]
My config setup:
![2018-11-02 16-53-15](https://user-images.githubusercontent.com/35327931/47904404-098b2080-dec0-11e8-84cb-2929703891d8.png)
![2018-11-02 16-53-49](https://user-images.githubusercontent.com/35327931/47904406-098b2080-dec0-11e8-93f5-e4269f9af0cc.png)

**Comment by ericosmic** [comment]
the error message:
![2018-11-02 16-50-44](https://user-images.githubusercontent.com/35327931/47904557-3dfedc80-dec0-11e8-9e24-29496acd761f.png)

**Comment by salu133445** [comment]
Oh...I see. You are using the source code from another repo (musegan). I found the bug. You need to change the following line in `main.py`:

```python
if CONFIG['train']['training_phase'] == 'two_stage':
```

to 

```python
if CONFIG['train']['training_phase'] == 'second_stage':
```

**Comment by ericosmic** [comment]
Thanks ,I would change the config and retry.  Actually ,   I have another doubt  when the mode is training , it  would often give a warning like this:
![2018-11-02 17-59-36](https://user-images.githubusercontent.com/35327931/47908864-3132b680-dec9-11e8-80dc-3dda78729112.png)
What is reason about it ?   
If it would affect the result of training?

**Comment by salu133445** [comment]
That won't affect the training. You can suppress it by modifying part of the source code in function `tonal_dist` in `bmusegan/musegan/utils/metric.py` to:
```python
with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=RuntimeWarning)
        chroma1 = chroma1 / np.sum(chroma1)
        chroma2 = chroma2 / np.sum(chroma2)
    result1 = np.matmul(tonal_matrix, chroma1)
    result2 = np.matmul(tonal_matrix, chroma2)
```
