### ISSUE TITLE
OOM problem for train stage 

### ISSUE THREAD

**Issue by ericosmic** [salu133445/bmusegan#4]
When I run the train stage (the second stage) of musegan/bmusegan  , it would jump out  and remind me the OOM problem 
![2018-11-05 10-17-58](https://user-images.githubusercontent.com/35327931/47974726-e0e47000-e0e5-11e8-924b-b6eafd4bc7b7.png)
But at same time  , my GPU memory >10G for free,  it is weird.    Do you know what is problem? 
![2018-11-05 10-32-57](https://user-images.githubusercontent.com/35327931/47974804-33be2780-e0e6-11e8-9769-ee0c6aaf2f9c.png)

**Comment by salu133445** [comment]
You need to reduce the batch size used in the second-stage training. We used 32 for the first stage and 16 for the second stage.
