### ISSUE TITLE
Failed to interpret file 'lastfm_alternative_8b_phrase.npy' as a pickle

### ISSUE THREAD

**Issue by Robrib** [salu133445/bmusegan#5]
Hi, I downloaded the data 'lastfm_alternative_8b_phrase.npy' and I tried this command: python **store_to_sa.py lastfm_alternative_8b_phrase.npy --name=lastfm_alternative_8b_phrase** 

And it said that: Failed to interpret file 'lastfm_alternative_8b_phrase.npy' as a pickle

**Comment by salu133445** [comment]
It seems that the old download script is not working. I have updated it. It should work now, so please run the download script again. You may want to check the file size to see whether it succeeds.
